// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hCT1a5zuYcXYJ2Jyr8Bv_L6AL_Y1ovA',
    appId: '1:328260367659:web:fcd044b73859542b86816e',
    messagingSenderId: '328260367659',
    projectId: 'bullan-de4de',
    authDomain: 'bullan-de4de.firebaseapp.com',
    storageBucket: 'bullan-de4de.firebasestorage.app',
    measurementId: 'G-ZBVMS4DFCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgaQN9Sb1v0zTgZP1k3kKKxX8SJiqpz_A',
    appId: '1:328260367659:android:114525a5e91ac70486816e',
    messagingSenderId: '328260367659',
    projectId: 'bullan-de4de',
    storageBucket: 'bullan-de4de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfUCABNaUWPk95mdM8DSq5_OJnl0cGggM',
    appId: '1:328260367659:ios:771501c97e22520286816e',
    messagingSenderId: '328260367659',
    projectId: 'bullan-de4de',
    storageBucket: 'bullan-de4de.firebasestorage.app',
    iosBundleId: 'com.example.bullan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfUCABNaUWPk95mdM8DSq5_OJnl0cGggM',
    appId: '1:328260367659:ios:771501c97e22520286816e',
    messagingSenderId: '328260367659',
    projectId: 'bullan-de4de',
    storageBucket: 'bullan-de4de.firebasestorage.app',
    iosBundleId: 'com.example.bullan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1hCT1a5zuYcXYJ2Jyr8Bv_L6AL_Y1ovA',
    appId: '1:328260367659:web:3716dd2c8cf07d2a86816e',
    messagingSenderId: '328260367659',
    projectId: 'bullan-de4de',
    authDomain: 'bullan-de4de.firebaseapp.com',
    storageBucket: 'bullan-de4de.firebasestorage.app',
    measurementId: 'G-QVBKX0PSHR',
  );
}
